### PR TITLE
feat: add `--select-found` flag

### PR DESCRIPTION
**Pull request by yajo**
Easy way to get all available addons to the current environment (or path selection).

Closes https://github.com/sbidoul/manifestoo/issues/17.

### CODE REVIEW

**Comment by sbidoul** [comment]
CI is now green

**Comment by yajo** [comment]
Thanks! I rebased, but it seems you need to approve the run.

**Comment by sbidoul** [comment]
LGTM, thanks for the contrib! Can you add a newfragment (`news/17.feature`)?

**Comment by sbidoul** [comment]
Ah, and cherry on the cake would be an update to the documentation page: https://github.com/sbidoul/manifestoo/blob/main/docs/addons_selection.md (I'll regenerate CLI reference  upon release).

**Pull request merged**
